name: Publish to VS Code Marketplace

on:
  release:
    types: [published]
  workflow_dispatch:  # Allow manual triggering

jobs:
  publish:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Build extension
      run: npm run package
    
    - name: Install vsce
      run: npm install -g @vscode/vsce
    
    - name: Package extension
      run: vsce package
    
    - name: Publish to VS Code Marketplace
      env:
        VSCE_PAT: ${{ secrets.VSCE_PAT }}
      run: vsce publish -p $VSCE_PAT
    
    - name: Upload VSIX to Release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./railway-monitor-${{ github.event.release.tag_name }}.vsix
        asset_name: railway-monitor-${{ github.event.release.tag_name }}.vsix
        asset_content_type: application/zip