name: Bump Version

# This workflow automates version bumping
# Just run it from GitHub Actions and select version type
# It will handle all git operations automatically

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version type (major, minor, patch)'
        required: true
        default: 'patch'
        type: choice
        options:
          - patch
          - minor
          - major

jobs:
  bump-version:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
    
    - name: Configure Git
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
    
    - name: Install dependencies
      run: npm ci
    
    - name: Bump version
      run: |
        npm version ${{ github.event.inputs.version }} --no-git-tag-version
        VERSION=$(node -p "require('./package.json').version")
        git add package.json package-lock.json
        git commit -m "chore: bump version to ${VERSION}"
        git tag -a "v${VERSION}" -m "Version ${VERSION}"
    
    - name: Push changes
      run: |
        git push
        git push --tags
    
    - name: Get package version
      id: package-version
      run: echo "current-version=$(node -p \"require('./package.json').version\")" >> $GITHUB_OUTPUT
    
    - name: Create Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v${{ steps.package-version.outputs.current-version }}
        release_name: Release v${{ steps.package-version.outputs.current-version }}
        body: |
          ## Changes in this release
          - Version bump from workflow dispatch
          
          **Note:** This release has been created but not yet published to the VS Code Marketplace.
          To publish, run the "Publish to VS Code Marketplace" workflow.
          
          See [commit history](https://github.com/${{ github.repository }}/commits/v${{ steps.package-version.outputs.current-version }}) for details.
        draft: false
        prerelease: false